[package]
name = "start-rust"
version = "0.1.0"
authors = ["jasper <63331153+jasper-oh@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
rand = "0.8.5"